# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular Full CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install dependencies
    - run: npm ci
    - name: Build Angular Project
    - run: npm run build
    - name: Success
    - if: success()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test Based On Job (Success)
        conclusion: ${{ job.status }}
